# Generated by Django 4.2 on 2023-04-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cardid', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('f_ingreso', models.DateField(null=True)),
                ('h_ingreso', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'LiveData',
            },
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cardid', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('f_evento', models.DateField(null=True)),
                ('h_evento', models.TimeField(null=True)),
                ('evento', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Marcacion',
            },
        ),
        migrations.CreateModel(
            name='NoRegistrados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cardid', models.IntegerField()),
                ('f_evento', models.DateField(null=True)),
                ('h_evento', models.TimeField(null=True)),
                ('evento', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'NoRegistrados',
            },
        ),
        migrations.CreateModel(
            name='PersonalRegistrado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cardid', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(null=True)),
                ('f_nac', models.DateField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PersonalRegistrado',
            },
        ),
    ]
