# Generated by Django 4.2 on 2023-04-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
