# Generated by Django 4.2 on 2023-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_livedata_cardid_remove_marcacion_cardid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceID',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deviceID', models.CharField(max_length=8, null=True)),
                ('ubicacion', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'deviceID',
            },
        ),
    ]
