# Generated by Django 4.2 on 2023-04-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_deviceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=8, null=True)),
                ('cardidHex', models.CharField(max_length=8, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('f_evento', models.DateField(null=True)),
                ('h_evento', models.TimeField(null=True)),
                ('evento', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Historial',
            },
        ),
        migrations.DeleteModel(
            name='Marcacion',
        ),
        migrations.AddField(
            model_name='livedata',
            name='ubicacion',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='noregistrados',
            name='ubicacion',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
