# Generated by Django 4.2 on 2023-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_historial_delete_marcacion_livedata_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
