# Generated by Django 4.2 on 2023-04-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_historial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noregistrados',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
