# Generated by Django 4.2 on 2023-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_livedata_cardidhex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='cardidHex',
            field=models.CharField(default='XXXXXXXX', max_length=8),
            preserve_default=False,
        ),
    ]
