# Generated by Django 4.2 on 2023-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCardIDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardid', models.IntegerField()),
                ('f_evento', models.DateField(null=True)),
                ('h_evento', models.TimeField(null=True)),
                ('evento', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
